In [1]:
print("hello madaarchod")

hello madaarchod


In [1]:
import numpy as np

print(np.__version__)

2.1.3


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr=np.array((1,2,3,4,5,6))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#Array Examples
#1-D Array
#2-D Array
#3-D Array

In [ ]:
#0-D Array
import numpy as np
arr=np.array(23)
print(arr)

23


In [6]:
#1-D Array
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [7]:
#2-D Array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#3-D Array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
#Dimension Check
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [13]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
#Array Slicing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [ ]:
#Numpy data types

In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [19]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5] ,dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [23]:
#Alternate Method

In [25]:
import numpy as np
arr=np.array([1,22,3,4,5])
newarr=arr.astype('S')
print(newarr)

[b'1' b'22' b'3' b'4' b'5']


In [26]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [27]:
#COPY vs VIEW

In [28]:
#COPY
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [29]:
#VIEW
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [30]:
#As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

#Every NumPy array has the attribute base that returns None if the array owns the data.

#Otherwise, the base  attribute refers to the original object.

In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

#A copy creates a new array with its own memory.

#A view is just a window into the original array's memory — it doesn't own the data.

None
[1 2 3 4 5]


In [33]:
#SHAPE 
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [35]:
#RESHAPE

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
#It is a VIEW

[1 2 3 4 5 6 7 8]


In [ ]:
#Unknown Dimension

In [39]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#You are allowed to have one "unknown" dimension.

#Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

#Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
#Flattening the arrays

In [ ]:
#Flattening array means converting a multidimensional array into a 1D array.

#We can use reshape(-1) to do this.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
